import { EProjectStatus, EProjectVisibility } from "@/types/enums";
import type { IProjectWithRelations } from "@/types/project";

export type TProjectRow = IProjectWithRelations & { year: number; province: string; city: string };

const picList = [
    {
        id: "u1",
        name: "Akbar Anugrah",
        email: "akbar@paris.co.id",
        phone: 0,
        google_token: "",
        roleId: "r1",
        password: "",
        createdAt: "",
        updatedAt: "",
        deleted: false,
    },
    {
        id: "u2",
        name: "Syuhada Asdini",
        email: "syuhada@paris.co.id",
        phone: 0,
        google_token: "",
        roleId: "r1",
        password: "",
        createdAt: "",
        updatedAt: "",
        deleted: false,
    },
    {
        id: "u3",
        name: "Iska Gushilman",
        email: "iska@paris.co.id",
        phone: 0,
        google_token: "",
        roleId: "r1",
        password: "",
        createdAt: "",
        updatedAt: "",
        deleted: false,
    },
];

export const dummyProjects: TProjectRow[] = [
    {
        id: "1",
        clientId: "c1",
        picId: "u1",
        name: "Survei Investigasi dan Desain Percetakan Sawah Sumatera Selatan",
        totalContractValue: 1_850_000_000,
        totalBudget: 1_600_000_000,
        totalCost: 820_000_000,
        startDate: "2025-01-15",
        endDate: "2025-12-31",
        status: EProjectStatus.PROCESS,
        visibility: EProjectVisibility.PUBLIC,
        access_code: "UNPAD-01",
        files: [],
        createdAt: "2025-01-15",
        updatedAt: "2025-04-10",
        deleted: false,
        year: 2025,
        province: "Sumatera Selatan",
        city: "Palembang",
        client: { id: "c1", name: "Universitas Padjadjaran", phone: 0, address: "Bandung", createdAt: "", updatedAt: "", deleted: false },
        pic: picList[0],
    },
    {
        id: "2",
        clientId: "c2",
        picId: "u2",
        name: "Penyusunan Dokumen Feasibility Study Tambang Nikel Lingkup Lingkungan dan Sosial",
        totalContractValue: 3_200_000_000,
        totalBudget: 2_900_000_000,
        totalCost: 1_450_000_000,
        startDate: "2025-02-01",
        endDate: "2025-11-30",
        status: EProjectStatus.PROCESS,
        visibility: EProjectVisibility.PRIVATE,
        access_code: "CSM-63",
        files: [],
        createdAt: "2025-02-01",
        updatedAt: "2025-04-15",
        deleted: false,
        year: 2025,
        province: "Sulawesi Tengah",
        city: "Morowali",
        client: { id: "c2", name: "PT Citra Silika Mallawa", phone: 0, address: "Jakarta", createdAt: "", updatedAt: "", deleted: false },
        pic: picList[1],
    },
    {
        id: "3",
        clientId: "c3",
        picId: "u3",
        name: "Penyusunan UKL-UPL SPBU di Kabupaten Banyuasin",
        totalContractValue: 480_000_000,
        totalBudget: 420_000_000,
        totalCost: 310_000_000,
        startDate: "2025-03-10",
        endDate: "2025-09-30",
        status: EProjectStatus.DONE,
        visibility: EProjectVisibility.PUBLIC,
        access_code: "MAJ-64",
        files: [],
        createdAt: "2025-03-10",
        updatedAt: "2025-04-20",
        deleted: false,
        year: 2025,
        province: "Sumatera Selatan",
        city: "Banyuasin",
        client: { id: "c3", name: "PT Mulia Andhika Jaya", phone: 0, address: "Palembang", createdAt: "", updatedAt: "", deleted: false },
        pic: picList[2],
    },
    {
        id: "4",
        clientId: "c4",
        picId: "u4",
        name: "Penyusunan Dokumen Feasibility Study Tambang Nikel Lingkup Lingkungan dan Sosial",
        totalContractValue: 3_400_000_000,
        totalBudget: 3_000_000_000,
        totalCost: 0,
        startDate: "2025-04-01",
        endDate: "2025-12-31",
        status: EProjectStatus.PROCESS,
        visibility: EProjectVisibility.PRIVATE,
        access_code: "PUL-65",
        files: [],
        createdAt: "2025-04-01",
        updatedAt: "2025-04-21",
        deleted: false,
        year: 2025,
        province: "Sulawesi Tenggara",
        city: "Konawe",
        client: { id: "c4", name: "PT Prima Utama Lestari", phone: 0, address: "Makassar", createdAt: "", updatedAt: "", deleted: false },
        pic: picList[0],
    },
    {
        id: "5",
        clientId: "c5",
        picId: "u5",
        name: "Penyusunan Dokumen Rencana Pascatambang",
        totalContractValue: 920_000_000,
        totalBudget: 800_000_000,
        totalCost: 750_000_000,
        startDate: "2025-01-20",
        endDate: "2025-08-31",
        status: EProjectStatus.DONE,
        visibility: EProjectVisibility.PUBLIC,
        access_code: "TJ-66",
        files: [],
        createdAt: "2025-01-20",
        updatedAt: "2025-04-18",
        deleted: false,
        year: 2025,
        province: "Kalimantan Timur",
        city: "Balikpapan",
        client: { id: "c5", name: "PT Tanur Jaya", phone: 0, address: "Balikpapan", createdAt: "", updatedAt: "", deleted: false },
        pic: picList[1],
    },
    {
        id: "6",
        clientId: "c6",
        picId: "u6",
        name: "Survei dan Kajian Rencana Pelaksanaan Area Reklamasi Tambang Nikel",
        totalContractValue: 1_750_000_000,
        totalBudget: 1_500_000_000,
        totalCost: 400_000_000,
        startDate: "2025-05-01",
        endDate: "2025-12-31",
        status: EProjectStatus.HOLD,
        visibility: EProjectVisibility.PRIVATE,
        access_code: "ASP-67",
        files: [],
        createdAt: "2025-05-01",
        updatedAt: "2025-04-22",
        deleted: false,
        year: 2025,
        province: "Sulawesi Tengah",
        city: "Morowali Utara",
        client: { id: "c6", name: "PT Anugerah Surya Pratama", phone: 0, address: "Sulawesi Tengah", createdAt: "", updatedAt: "", deleted: false },
        pic: picList[2],
    },
    {
        id: "7",
        clientId: "c7",
        picId: "u7",
        name: "Kajian Alih Fungsi Lahan Pertanian Pangan Berkelanjutan (LP2B) Jalan Tol Sigli – Banda Aceh",
        totalContractValue: 4_200_000_000,
        totalBudget: 3_800_000_000,
        totalCost: 1_900_000_000,
        startDate: "2025-03-01",
        endDate: "2025-12-31",
        status: EProjectStatus.PROCESS,
        visibility: EProjectVisibility.PRIVATE,
        access_code: "HK-68",
        files: [],
        createdAt: "2025-03-01",
        updatedAt: "2025-04-20",
        deleted: false,
        year: 2025,
        province: "Aceh",
        city: "Pidie",
        client: { id: "c7", name: "PT Hutama Karya (Persero)", phone: 0, address: "Jakarta", createdAt: "", updatedAt: "", deleted: false },
        pic: picList[0],
    },
    {
        id: "8",
        clientId: "c8",
        picId: "u8",
        name: "Penyusunan Dokumen Rencana Reklamasi",
        totalContractValue: 1_100_000_000,
        totalBudget: 950_000_000,
        totalCost: 0,
        startDate: "2026-01-10",
        endDate: "2026-10-31",
        status: EProjectStatus.PROCESS,
        visibility: EProjectVisibility.PRIVATE,
        access_code: "EPN-69",
        files: [],
        createdAt: "2026-01-10",
        updatedAt: "2026-04-01",
        deleted: false,
        year: 2026,
        province: "Kalimantan Tengah",
        city: "Kotawaringin Timur",
        client: { id: "c8", name: "PT Energy Persada Nusantara", phone: 0, address: "Jakarta", createdAt: "", updatedAt: "", deleted: false },
        pic: picList[1],
    },
    {
        id: "9",
        clientId: "c1",
        picId: "u3",
        name: "Survei Investigasi dan Desain Percetakan Sawah Jambi dan Sumatera Selatan",
        totalContractValue: 2_100_000_000,
        totalBudget: 1_850_000_000,
        totalCost: 0,
        startDate: "2026-02-01",
        endDate: "2026-12-31",
        status: EProjectStatus.PROCESS,
        visibility: EProjectVisibility.PUBLIC,
        access_code: "UNPAD-70",
        files: [],
        createdAt: "2026-02-01",
        updatedAt: "2026-04-10",
        deleted: false,
        year: 2026,
        province: "Jambi",
        city: "Muaro Jambi",
        client: { id: "c1", name: "Universitas Padjadjaran", phone: 0, address: "Bandung", createdAt: "", updatedAt: "", deleted: false },
        pic: picList[2],
    },
    {
        id: "10",
        clientId: "c9",
        picId: "u2",
        name: "Penyusunan Feasibility Study dan Masterplan Kawasan Industri Nikel",
        totalContractValue: 6_500_000_000,
        totalBudget: 5_800_000_000,
        totalCost: 0,
        startDate: "2026-03-01",
        endDate: "2026-12-31",
        status: EProjectStatus.PROCESS,
        visibility: EProjectVisibility.PRIVATE,
        access_code: "BTIIG-71",
        files: [],
        createdAt: "2026-03-01",
        updatedAt: "2026-04-15",
        deleted: false,
        year: 2026,
        province: "Sulawesi Tengah",
        city: "Palu",
        client: {
            id: "c9",
            name: "Baoshuo Taman Industri Investment Grup (BTIIG)",
            phone: 0,
            address: "Jakarta",
            createdAt: "",
            updatedAt: "",
            deleted: false,
        },
        pic: picList[0],
    },
];
